syntax = 'LuaJIT'
call_parentheses = "Always"
collapse_simple_statement = "Never"
column_width = 120
indent_type = "Tabs"
indent_width = 4
line_endings = "Unix"
quote_style = "AutoPreferDouble"
space_after_function_names = "Never"

[sort_requires]
enabled = false
